on:
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  comment_pr:
    name: Initial PR Comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR with body
        uses: jimmy-ens/pr-action@v1
        id: init-pr-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The first comment on the PR - Current branch is `${{ github.head_ref }}`.
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
          comment-tag: init-pr-comment
          reactions: eyes, rocket
          mode: recreate

      - name: Check outputs
        run: |
          echo "pr-id :${{ github.event.pull_request.number }}"
          echo "comment-id : ${{ steps.init-pr-comment.id }}"
          echo "body : ${{ steps.init-pr-comment.outputs.body }}"
          echo "html-url : ${{ steps.init-pr-comment.outputs.html-url }}"