name: Additional PR Comment

on:
  pull_request_target:
    types: [edited, reopened, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  comment_pr:
    name: PR Comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR with body
        uses: peter-evans/create-or-update-comment@v4
#        id: additional-pr-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Additional comment on the PR.
          comment-tag: init-pr-comment
          reactions: +1
          mode: recreate

      - name: Check outputs
        run: |
          echo "pr-id :${{ github.event.pull_request.number }}"
          echo "comment-id : ${{ steps.comment_pr.outputs.id }}"
          echo "body : ${{ steps.comment_pr.outputs.body }}"
          echo "html-url : ${{ steps.comment_pr.outputs.html-url }}"